
name: 'fdr_eaupotable'
version: '0.1'
profile: 'fdr_eaupotable'
config-version: 2
#require-dbt-version: '0.21.0'

vars:
  #limit: 1000
  FDR_CAS_USAGE: eaupotable
  ns: 'canalisation.eaupotable.francedatareseau.fr' # access with var('ns')
  enableOverTime: false # sinon problèmes, voir dans les exploitation/*_ot.sql
  enableProfiling: false
  test_extract_suffixes:
    #- _extract_stg
    #- _extract
    - _example_stg
    - _example
    #- _definition_stg
    #- _definition
  # TODO (level of) enablement of each source
  # TODO or / and setup/conf() macros
  # TODO move to global meta project :
  schemas: ['appuiscommuns', 'sdirve', 'eaupotable', 'eclairage_public']

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

on-run-start:
    #- '{{create_role_schema("appuiscommuns")}}' KO in THIS project, must exist for DBT to run...
    # so rather in a meta project OR OPERATION AS ADMIN
    #- '{{create_role_schema("appuiscommuns_test")}}'
    ##- '{% if not target.name %}{{create_views()}}{% endif %}'
    - '{{ fdr_appuiscommuns.create_udfs() }}'
    
seeds:
  # TODO temp, rm :
  fdr_appuiscommuns:
    +enabled: false
  fdr_eaupotable:
    #+quote_columns: true now true by default in 1.0
    # seed-specific conf is now in its own source yml files

#sources:
#  appuiscommuns_osmgeodataminepowersupports:
#    mysource:
#      mytable:
#        +enabled: false

models:
  # enable incremental schema update : TODO for now KO because doesn't quote field https://github.com/dbt-labs/dbt-core/issues/4423
  #+on_schema_change: "sync_all_columns"
  # TODO temp, rm :
  fdr_appuiscommuns:
    +enabled: false
  #fdr_osmgeodatamine_powersupports:
  fdr_eaupotable:
    # TODO move to _unified /_joined / _computed/enriched ?
    # sources :
    materialized: view
    #staging:
    eaupot:
      materialized: table
      # TODO separate _indicators/aggregates from _views etc.
      exploitation:
        #materialized: view NO rather table for performance
    #meta:
      #materialized: table not needed (?)
